SELECT 
    E.EventName,
    D.Division,
    G.Gender,
    C.Category,
    RND.Round,
	RND.Round_ID,
    CASE G.Gender_ID
        WHEN 2 THEN --Female
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128FemaleSimul--R128
                WHEN 10 THEN D.Ro64FemaleSimul--R64
                WHEN 11 THEN D.Ro32FemaleSimul--R32
                WHEN 12 THEN D.Ro16FemaleSimul--R16
                WHEN 13 THEN D.Ro8FemaleSimul--R8
                WHEN 14 THEN D.Ro4FemaleSimul--R4
                WHEN 15 THEN D.Ro2FemaleSimul--R2
                ELSE 0
            END 
        ELSE --Male & Coed
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128MaleSimul--R128
                WHEN 10 THEN D.Ro64MaleSimul--R64
                WHEN 11 THEN D.Ro32MaleSimul--R32
                WHEN 12 THEN D.Ro16MaleSimul--R16
                WHEN 13 THEN D.Ro8MaleSimul--R8
                WHEN 14 THEN D.Ro4MaleSimul--R4
                WHEN 15 THEN D.Ro2MaleSimul--R2
                ELSE 0
            END 
        END AS Simultaneous,
	P.OrderOfPerform, 
	P.CompetitorNbr , 
	P.FormName_A, 
	P.Acc_R_A, 
	P.Acc_J1_A, 
	P.Acc_J2_A, 
	P.Acc_J3_A, 
	P.Acc_J4_A, 
	P.Acc_J5_A, 
	P.Acc_J6_A, 
	P.Acc_Avg_A, 
	P.Pre_R_A, 
	P.Pre_J1_A, 
	P.Pre_J2_A, 
	P.Pre_J3_A, 
	P.Pre_J4_A, 
	P.Pre_J5_A, 
	P.Pre_J6_A, 
	P.Pre_Avg_A,  
	P.Pen_OT_A, 
	P.Pen_OOB_A, 
	P.Form_Score_A, 
	P.FormName_B, 
	P.Acc_R_B, 
	P.Acc_J1_B, 
	P.Acc_J2_B, 
	P.Acc_J3_B, 
	P.Acc_J4_B, 
	P.Acc_J5_B, 
	P.Acc_J6_B, 
	P.Acc_Avg_B, 
	P.Pre_R_B, 
	P.Pre_J1_B, 
	P.Pre_J2_B, 
	P.Pre_J3_B, 
	P.Pre_J4_B, 
	P.Pre_J5_B, 
	P.Pre_J6_B, 
	P.Pre_Avg_B, 
	P.Pen_OT_B, 
	P.Pen_OOB_B, 
	P.Form_Score_B, 
	P.Form_Score_AB, 
	P.Presentation_Total, 
	P.Full_Score, 
	P.TieBreaker_Score, 
	P.TieBreaker_Total, 
	P.TieBreaker_needed, 
	P.FormName_T, 
	P.Acc_R_T, 
	P.Acc_J1_T, 
	P.Acc_J2_T, 
	P.Acc_J3_T, 
	P.Acc_J4_T, 
	P.Acc_J5_T, 
	P.Acc_J6_T, 
	P.Acc_Avg_T, 
	P.Pre_R_T, 
	P.Pre_J1_T, 
	P.Pre_J2_T, 
	P.Pre_J3_T, 
	P.Pre_J4_T, 
	P.Pre_J5_T, 
	P.Pre_J6_T, 
	P.Pre_Avg_T, 
	P.Pen_OT_T, 
	P.Pen_OOB_T
FROM 
    Events E,
    PoomsaeScores P,
    GenderTbl G,
    DivisionNames D,
    CategoryTbl C,
    RoundTbl RND
WHERE
    E.DatabaseID = P.DatabaseID
    AND G.DatabaseID = E.DatabaseID AND G.Gender_ID = P.Gender
    AND D.DatabaseID = E.DatabaseID AND D.Division_ID = P.Division
    AND C.DatabaseID = E.DatabaseID AND P.Category = C.Category_ID
    AND RND.DatabaseID = E.DatabaseID AND RND.Round_ID = P.RoundName
    AND P.Acc_R_A <> -1 --Competition Happened
    AND D.CompMeth_Black IN (1, 4) --Single Elimination Top 8 of Combination
    AND RND.Round_ID >= 9
    AND P.CompetitorNbr > 0 --Negative numbers are system generated BYES
