SELECT 
    E.EventName,
    D.Division,
    G.Gender,
    C.Category,
    RND.Round,
    CASE (P.OrderofPerform % 2) WHEN 1 THEN 'Chung' ELSE 'Hong' END AS Winner,
    CASE G.Gender_ID
        WHEN 2 THEN --Female
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128FemaleSimul--R128
                WHEN 10 THEN D.Ro64FemaleSimul--R64
                WHEN 11 THEN D.Ro32FemaleSimul--R32
                WHEN 12 THEN D.Ro16FemaleSimul--R16
                WHEN 13 THEN D.Ro8FemaleSimul--R8
                WHEN 14 THEN D.Ro4FemaleSimul--R4
                WHEN 15 THEN D.Ro2FemaleSimul--R2
                ELSE 0
            END 
        ELSE --Male & Coed
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128MaleSimul--R128
                WHEN 10 THEN D.Ro64MaleSimul--R64
                WHEN 11 THEN D.Ro32MaleSimul--R32
                WHEN 12 THEN D.Ro16MaleSimul--R16
                WHEN 13 THEN D.Ro8MaleSimul--R8
                WHEN 14 THEN D.Ro4MaleSimul--R4
                WHEN 15 THEN D.Ro2MaleSimul--R2
                ELSE 0
        END 
    END AS Simultaneous,
	(SELECT PN.Poomsae FROM Poomsae PN WHERE
		E.DatabaseID = PN.DatabaseID
		AND PN.Poomsae_ID = (
			CASE G.Gender_ID
				WHEN 2 THEN --Female
					CASE RND.Round_ID
						WHEN 9 THEN D.Ro128Female1--R128
						WHEN 10 THEN D.Ro64Female1--R64
						WHEN 11 THEN D.Ro32Female1--R32
						WHEN 12 THEN D.Ro16Female1--R16
						WHEN 13 THEN D.Ro8Female1--R8
						WHEN 14 THEN D.Ro4Female1--R4
						WHEN 15 THEN D.Ro2Female1--R2
						ELSE 'NONE'
					END 
				ELSE --Male & Coed
					CASE RND.Round_ID
						WHEN 9 THEN D.Ro128Male1--R128
						WHEN 10 THEN D.Ro64Male1--R64
						WHEN 11 THEN D.Ro32Male1--R32
						WHEN 12 THEN D.Ro16Male1--R16
						WHEN 13 THEN D.Ro8Male1--R8
						WHEN 14 THEN D.Ro4Male1--R4
						WHEN 15 THEN D.Ro2Male1--R2
						ELSE 'NONE'
				END 
			END)
	)AS Poomsae1,
		(SELECT PN.Poomsae FROM Poomsae PN WHERE
		E.DatabaseID = PN.DatabaseID
		AND PN.Poomsae_ID = (
			CASE G.Gender_ID
				WHEN 2 THEN --Female
					CASE RND.Round_ID
						WHEN 9 THEN D.Ro128Female2--R128
						WHEN 10 THEN D.Ro64Female2--R64
						WHEN 11 THEN D.Ro32Female2--R32
						WHEN 12 THEN D.Ro16Female2--R16
						WHEN 13 THEN D.Ro8Female2--R8
						WHEN 14 THEN D.Ro4Female2--R4
						WHEN 15 THEN D.Ro2Female2--R2
						ELSE 'NONE'
					END 
				ELSE --Male & Coed
					CASE RND.Round_ID
						WHEN 9 THEN D.Ro128Male2--R128
						WHEN 10 THEN D.Ro64Male2--R64
						WHEN 11 THEN D.Ro32Male2--R32
						WHEN 12 THEN D.Ro16Male2--R16
						WHEN 13 THEN D.Ro8Male2--R8
						WHEN 14 THEN D.Ro4Male2--R4
						WHEN 15 THEN D.Ro2Male2--R2
						ELSE 'NONE'
				END 
			END)
	)AS Poomsae2
FROM 
    Events E,
    PoomsaeScores P,
    GenderTbl G,
    DivisionNames D,
    CategoryTbl C,
    RoundTbl RND
WHERE
    E.DatabaseID = P.DatabaseID
    AND G.DatabaseID = E.DatabaseID AND G.Gender_ID = P.Gender
    AND D.DatabaseID = E.DatabaseID AND D.Division_ID = P.Division
    AND C.DatabaseID = E.DatabaseID AND P.Category = C.Category_ID
    AND RND.DatabaseID = E.DatabaseID AND RND.Round_ID = P.RoundName
    AND P.Acc_R_A <> -1 --Competition Happened
    AND D.CompMeth_Black IN (1, 4) --Single Elimination Top 8 of Combination
    AND RND.Round_ID >= 9
    AND P.Placement IN (0, 1) --Winner has no place except last match
    AND P.CompetitorNbr > 0 --Negative numbers are system generated BYES
