SELECT 
    E.EventName,
    D.Division,
    G.Gender,
    C.Category,
    RND.Round,
    CASE (P.OrderofPerform % 2) WHEN 0 THEN 'Chung' ELSE 'Hong' END AS Winner,
    CASE G.Gender_ID
        WHEN 2 THEN --Female
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128FemaleSimul--R128
                WHEN 10 THEN D.Ro64FemaleSimul--R64
                WHEN 11 THEN D.Ro32FemaleSimul--R32
                WHEN 12 THEN D.Ro16FemaleSimul--R16
                WHEN 13 THEN D.Ro8FemaleSimul--R8
                WHEN 14 THEN D.Ro4FemaleSimul--R4
                WHEN 15 THEN D.Ro2FemaleSimul--R2
                ELSE 0
            END 
        ELSE --Male & Coed
            CASE RND.Round_ID
                WHEN 9 THEN D.Ro128MaleSimul--R128
                WHEN 10 THEN D.Ro64MaleSimul--R64
                WHEN 11 THEN D.Ro32MaleSimul--R32
                WHEN 12 THEN D.Ro16MaleSimul--R16
                WHEN 13 THEN D.Ro8MaleSimul--R8
                WHEN 14 THEN D.Ro4MaleSimul--R4
                WHEN 15 THEN D.Ro2MaleSimul--R2
                ELSE 0
            END 
        END AS Simultaneous
FROM 
    Events E,
    PoomsaeScores P,
    GenderTbl G,
    DivisionNames D,
    CategoryTbl C,
    RoundTbl RND
WHERE
    E.DatabaseID = P.DatabaseID
    AND G.DatabaseID = E.DatabaseID AND G.Gender_ID = P.Gender
    AND D.DatabaseID = E.DatabaseID AND D.Division_ID = P.Division
    AND C.DatabaseID = E.DatabaseID AND P.Category = C.Category_ID
    AND RND.DatabaseID = E.DatabaseID AND RND.Round_ID = P.RoundName
    AND P.Acc_R_A <> -1 --Competition Happened
    AND D.CompMeth_Black IN (1, 4) --Single Elimination Top 8 of Combination
    AND RND.Round_ID >= 9
    AND P.Placement IN (0, 1) --Winner has no place except last match
    AND P.CompetitorNbr > 0 --Negative numbers are system generated BYES
